# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-20 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=64, unique=True)),
                ('roles', models.ManyToManyField(to='account.Role')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
    ]
