# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191125_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(to='account.Permission'),
        ),
    ]
