# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191120_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='p_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='r_name',
            new_name='name',
        ),
    ]
