# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191121_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='realname',
            new_name='real_name',
        ),
    ]
