# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ac_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
