# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('username', models.TextField()),
                ('code', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('result', models.IntegerField(db_index=True, default=8)),
                ('info', models.TextField(blank=True, null=True)),
                ('language', models.TextField()),
                ('shared', models.BooleanField(default=False)),
                ('use_time_ms', models.IntegerField(default=0)),
                ('use_memory_m_bytes', models.IntegerField(default=0)),
                ('ip', models.TextField(null=True)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
            ],
            options={
                'db_table': 'submission',
                'ordering': ('-create_time',),
            },
        ),
    ]
