# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-05 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20191129_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='point',
            field=models.TextField(null=True),
        ),
    ]
