# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='enter_permission',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='rank_permission',
        ),
    ]
