# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_ac_total'),
        ('contest', '0002_auto_20191128_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registrants',
            field=models.ManyToManyField(related_name='registrants', to='account.User'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to='account.User'),
        ),
    ]
