# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteOJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'remote_oj',
            },
        ),
        migrations.CreateModel(
            name='RemoteOJAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('remote_oj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remoteoj.RemoteOJ')),
            ],
            options={
                'db_table': 'remote_account',
            },
        ),
    ]
