# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-21 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_auto_20191121_0006'),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(db_index=True)),
                ('oj', models.CharField(max_length=32)),
                ('is_public', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('input_desc', models.TextField(blank=True, null=True)),
                ('output_desc', models.TextField(blank=True, null=True)),
                ('samples', models.TextField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(default="['C', 'C++', 'Java', 'Python2', 'Python3']")),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('time_limit', models.IntegerField(default=1000)),
                ('memory_limit', models.IntegerField(default=512)),
                ('is_spj', models.BooleanField(default=False)),
                ('is_spj_compile_ok', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('score', models.IntegerField(default=100)),
                ('submit_total', models.IntegerField(default=0)),
                ('ac_total', models.IntegerField(default=0)),
                ('statistic_info', models.TextField(default='{}')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
            options={
                'db_table': 'problem',
                'ordering': ('create_time',),
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('bg_color', models.CharField(blank=True, max_length=32, null=True)),
                ('font_color', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'problem_tag',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(to='problem.ProblemTag'),
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together=set([('_id', 'contest')]),
        ),
    ]
