# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_remove_problem_oj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='_id',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
