# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-30 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20191129_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='languages',
            field=models.TextField(default='["C", "C++", "Java", "Python2", "Python3"]'),
        ),
    ]
